### ISSUE TITLE
How did you get a `PyodideInstance` without having it as a `dependencies` in your `package.json`?

### ISSUE THREAD

**Issue by jymchng** [vwh/python-playground#22]
In your codes: https://github.com/vwh/python-playground/blob/main/src/types.ts#L12

This is the function you called in `initializePyodide`. I see that you don't have `pyodide` in your dependencies, then my questions are:

1. How do you at runtime get an instance of `pyodide`?
2. Why do you not want to add `pyodide` as one of your dependencies?

**Comment by vwh** [comment]
Hi

The file https://github.com/vwh/python-playground/blob/main/src/types.ts#L12 is juts a type declare am editing the global/window object 

I don't use it as dependencies am loading it from a CDN then store it on the window object 
https://github.com/vwh/python-playground/blob/main/index.html#L55
https://github.com/vwh/python-playground/blob/main/src/store/useStore.ts#L46

**Comment by vwh** [comment]
and "Why do you not want to add pyodide as one of your dependencies?"

I actually forgot why i did that but i think bcz it size or some thing like that

**Comment by jymchng** [comment]
Thank you for your response. Because right now in my Playground webapp, I am trying to implement install packages feature - after I do `await pyodide.loadPackage("pydantic", undefined, undefined, false); `, I get an integrity check error, so I am thinking of loading pyodide only at runtime - do you think this might work?
